name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    container: ${{ matrix.python-interpreter }}:${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        python-interpreter:
          - python
          - pypy

    steps:
      - uses: actions/checkout@v5

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        run: tox -e py

  coveralls:
    name: Test Coverage Measurement
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install coveralls
        run: pip3 install --upgrade tox coveralls

      - name: Run Tests
        run: tox -e coverage

      - name: Report Results
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lints:
    runs-on: ubuntu-latest
    name: flake8 Lints
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v6

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          path: "coolname"
