name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    container: ${{ matrix.python-interpreter }}:${{ matrix.python-version }}

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
        python-interpreter:
          - python
          - pypy
        exclude:
          - python-version: "3.12"
            python-interpreter: pypy
          - python-version: "3.13"
            python-interpreter: pypy
          - python-version: "3.14"
            python-interpreter: pypy

    steps:
      - uses: actions/checkout@v5

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        run: tox -e py

  coveralls:
    name: Test Coverage Measurement
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install coveralls
        run: pip3 install --upgrade tox coveralls

      - name: Run Tests
        run: tox -e coverage

      - name: Report Results
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lints:
    runs-on: ubuntu-latest
    name: flake8 Lints
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          path: "coolname"

  mypy_check:
    runs-on: ubuntu-latest
    name: mypy
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install tox
        run: pip install tox

      - name: Run mypy
        run: tox -e mypy
